### ISSUE TITLE
Only send request to calculate tax when a merchant has nexus

### ISSUE THREAD

**Issue by Noah-Silvera** [SuperGoodSoft/solidus_taxjar#140] opened 2022-01-03 21:49 UTC
https://developers.taxjar.com/integrations/certification-checklist/#section-sales-tax-calculations

> Avoid unnecessary API calls to v2/taxes by understanding the concept of a sales tax nexus. If a customer's delivery address is not in a state in which a merchant has nexus, no sales tax needs to be collected; therefore, there's no need to calculate tax.

 > * Keep in mind this only applies to US-based sales. Tax may need to be calculated for other jurisdictions.

**Comment by benjaminwil** [comment] 2022-02-03 18:37
Duplicate of #57 

Closing! ✨

**Closed by benjaminwil** 2022-02-03 18:37 UTC
Labels: enhancement
